image: drupalci/static_analysis:9.4.x

stages:
  - run-tests
  - analyze-job

analyze-job:
  stage: analyze-job
  parallel: 20
  retry: 2
  script:
    - cp -R ./* /var/lib/drupalci/workspace/infrastructure/stats/project_analysis/
    - wget https://www.drupal.org/files/project_analysis/projects.tsv?$CI_JOB_ID -O projects.tsv
    - split -n ${CI_NODE_INDEX}/${CI_NODE_TOTAL} projects.tsv > /var/lib/drupalci/workspace/projects.tsv

    - /var/lib/drupalci/workspace/infrastructure/stats/project_analysis/project_readiness.sh 9.4.x || true

    - mkdir artifacts
    - mv /var/lib/drupalci/workspace/phpstan-results artifacts
    - mv /var/lib/drupalci/workspace/projects.tsv artifacts
    - mv /var/lib/drupalci/workspace/analyzer_output.log artifacts
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
  artifacts:
    expose_as: "project_analysis"
    paths:
      - artifacts/projects.tsv
      - artifacts/analyzer_output.log
      - artifacts/phpstan-results
    expire_in: "1 month"
    when: always

run-unit-tests:
  stage: run-tests
  script:
    - cd project_analysis_utils
    - composer install
    - vendor/bin/phpunit tests/

run-bot-against-testset:
  stage: run-tests
  script:
    - cp -R ./* /var/lib/drupalci/workspace/infrastructure/stats/project_analysis/
    - cp project_analysis_utils/tests/project_list_files/projects_d10.tsv /var/lib/drupalci/workspace/projects.tsv
    - /var/lib/drupalci/workspace/infrastructure/stats/project_analysis/project_readiness.sh 9.4.x || true
    - mkdir artifacts
    - mv /var/lib/drupalci/workspace/phpstan-results artifacts
    - mv /var/lib/drupalci/workspace/projects.tsv artifacts
    - mv /var/lib/drupalci/workspace/analyzer_output.log artifacts
  artifacts:
    expose_as: "analysis_testoutput"
    paths:
      - artifacts/projects.tsv
      - artifacts/analyzer_output.log
      - artifacts/phpstan-results
    expire_in: "1 month"
    when: always
